name: Question
description: Have a question on how to use mdbook-embed?
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Got a question on how to do something with mdbook-embed?  
        Feel free to write to me!!
  - type: textarea
    id: question
    attributes:
      label: Question
      description: >
        Enter your question here. Please try to provide as much detail as possible.
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: >
        Please paste the output of running `mdbook-embed --version` or which version
        of the library you are using.
      render: text
